### ISSUE TITLE
VA Settings Is Complex

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#214]
**Is your feature request related to a problem? Please describe.**
When giving how you want the tracker to pick up your VA's pilots, the way to input your information could be clearer. Right now, mine looks like what I have put in the screenshot section, it would help a lot if it was clearer.

**Describe the solution you'd like**
Not quite sure. Maybe a spot for you to put the prefix and a spot to put the information after with # instead of numbers.

**Describe alternatives you've considered**
Annoy Kai until he walks me through it step by step.

**Additional context**
![Screen Shot 2020-10-19 at 8 27 20 AM](https://user-images.githubusercontent.com/71337097/96450990-eb21ab00-11e4-11eb-8000-0f927c9696da.png)

**Comment by Velocity23** [comment]
I'm afraid this won't be happening in the near future. I know RegEx is difficult but that's why the prefilled options are there. The variety of callsigns otherwise is just too wide, not to mention the fact that I'd somehow have to generate RegEx based on those more interactive dropdowns. I don't mind you bugging me though :wink:
